name: Pushing to
on: 
  push:
    branches:
      - 'feature/**'

env:
  DEPLOY_ENV: 'dev'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - run: pip install ruff
      - run: ruff .
  
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    steps:
    - run: pip install -r requirements.txt
    - name: Run Unit Tests
      run: python -m unittest discover -s src/tests -p "*.py"
    - name: Show Total Coverage Percentage
      run: coverage report | tail -n 1 | awk '{print "Total coverage - "$NF}'
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - run: echo "Deploying to $DEPLOY_ENV"


